### ISSUE TITLE
Installation fails due to dependencies

### ISSUE THREAD

**Issue by ahstro** [YunoHost-Apps/onlyoffice_ynh#29] opened 2020-03-18 09:15 UTC
When trying to install OnlyOffice, I'm ultimately met with this notification: "The operation 'Install 'onlyoffice' application' has failed! To get help, please provide the full log of this operation by clicking here".

[Here](https://gist.github.com/ahstro/ab22335ff558096232a66f50667af787) is the full log. There specifically seems to be a problem installing rabbitmq-server around [L647](https://gist.github.com/ahstro/ab22335ff558096232a66f50667af787#file-gistfile1-txt-L647).

I have no idea how to solve this, but with [Nextcloud 18](https://github.com/YunoHost-Apps/nextcloud_ynh/pull/260) being very much in the YunoHost-pipeline, it'd be amazing to get to use the OnlyOffice integration 😊

**Comment by decentral1se** [comment] 2020-03-19 00:04
Hey @ahstro, the full story is found in https://github.com/YunoHost-Apps/onlyoffice_ynh/issues/20. There doesn't seem to be one fix all solution but a number of approaches, all of which I've laid out under that ticket or linked from other reports. I'm going to close this as a duplicate of #20 and please update over there if you are still having trouble. Hope you can get this to work.

**Closed by decentral1se** 2020-03-19 00:04 UTC
